# Copyright 2025 Intel Corp.
# SPDX-License-Identifier: Apache-2.0

name: Setup SCA for Zephyr
description: Setup SCA tools

inputs:
  tool-name:
    description: |
      The tool to be used.
    required: true
  install-dir:
    description: |
      Installation directory
    required: true
  s3-access-key-id:
    description: |
      Access Key ID
    required: true
  s3-secret-access-key:
    description: |
      Secret Access Key
    required: true
  license-server:
    description: |
      License server for SCA tools.
    required: false
    default: ""

runs:
  using: "composite"
  steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
      with:
        aws-access-key-id: ${{ inputs.s3-access-key-id }}
        aws-secret-access-key: ${{ inputs.s3-secret-access-key }}
        aws-region: us-east-1

    - name: Set up Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: 3.12
        cache: pip
        cache-dependency-path: scripts/requirements-actions.txt

    - name: Install Python packages
      shell: bash
      run: |
        pip install awscli

    - name: Download and Unpack tool
      shell: bash
      run: |
        if [ "${{ inputs.tool-name }}" = "coverity" ]; then
          aws s3 cp --quiet  s3://tool-distribution.zephyrproject.org/coverity/cov-analysis-linux64-2024.6.1.tar.gz .
          mkdir -p ${{ inputs.install-dir }}
          tar xf cov-analysis-linux64-2024.6.1.tar.gz -C ${{ inputs.install-dir }}  --strip-components=1
          rm cov-analysis-linux64-2024.6.1.tar.gz
          echo "${{ inputs.install-dir }}/bin"  >> $GITHUB_PATH
        elif [  "${{ inputs.tool-name }}" = "eclair" ]; then
          aws s3 cp --quiet  s3://tool-distribution.zephyrproject.org/eclair/eclair-3.14.0.tar.bz2 .
          mkdir -p ${{ inputs.install-dir }}
          tar xf eclair-3.14.0.tar.bz2 -C ${{ inputs.install-dir }}  --strip-components=1
          rm eclair-3.14.0.tar.bz2
          ./${{ inputs.install-dir }}/bin/postinstall.sh
          echo "${{ inputs.install-dir }}/bin"  >> $GITHUB_PATH
          mkdir -p ~/.hasplm
          echo "[REMOTE]" >  ~/.hasplm/hasp_113938.ini
          echo "serveraddr = ${{ inputs.license-server }}" >>  ~/.hasplm/hasp_113938.ini
          echo "requestlog = 1" >>  ~/.hasplm/hasp_113938.ini
          echo "errorlog = 1" >> ~/.hasplm/hasp_113938.ini
        fi
